"A datetime string with format `Y-m-d H:i:s`, e.g. `2018-05-23 13:43:32`."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

"A date string with format `Y-m-d`, e.g. `2011-05-23`."
scalar Date @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\Date")

type Query {
    "Thông tin người dùng đang đăng nhập"
    me: User @auth
}

type Mutation {
    "Đăng nhập hệ thống (user)"
    login(input: LoginInput! @spread): AuthPayload
        @field(resolver: "App\\GraphQL\\Mutations\\Auth\\Login")

    "Đăng nhập hệ thống (admin)"
    adminLogin(input: LoginInput! @spread): AuthPayload
        @field(resolver: "App\\GraphQL\\Mutations\\Auth\\AdminLogin")

    "Yêu cầu đặt lại mật khẩu"
    forgotPassword(input: ForgotPasswordInput! @spread): ForgotPasswordPayload!
        @field(resolver: "App\\GraphQL\\Mutations\\Users\\ForgotPassword")

    "Đặt lại mật khẩu bằng token"
    resetPassword(input: ResetPasswordInput! @spread): ResetPasswordPayload!
        @field(resolver: "App\\GraphQL\\Mutations\\Users\\ResetPassword")
}

type ForgotPasswordPayload {
    message: String!
}

type ResetPasswordPayload {
    message: String!
}

extend type Mutation @guard {
    logout: Boolean!
        @field(resolver: "App\\GraphQL\\Mutations\\Auth\\Logout")
}

input LoginInput {
    email: String!
    password: String!
}

input ForgotPasswordInput @validator(class: "ForgotPasswordInputValidator") {
    email: String!
}

input ResetPasswordInput @validator(class: "ResetPasswordInputValidator") {
    token: String!
    email: String!
    password: String!
    password_confirmation: String!
}

type AuthPayload {
    access_token: String
    user: User
}

type User {
    id: ID!
    name: String!
    email: String!
    roles: [String!]! @method(name: "getRoleNames")
}



type HouseholdMember {
    id: ID!
    fullName: String! @rename(attribute: "full_name")
    gender: GenderEnum
    dateOfBirth: Date @rename(attribute: "date_of_birth")
    phone_number: String
    nationalId: String @rename(attribute: "national_id")
    relationship: HouseholdRelationship!
}


enum GenderEnum {
    MALE @enum(value: "male")
    FEMALE @enum(value: "female")
}

extend type Query @guard {
    "Thống kê tổng hợp dân cư"
    statistics: ResidentStatistics
        @hasPermission(name: "view statistics")
        @field(resolver: "App\\GraphQL\\Queries\\Statistics")
}

type ResidentStatistics {
    totalResidents:             Int @rename(attribute: "total_residents")
    totalHouseholds:            Int @rename(attribute: "total_households")
    maleCount:                  Int @rename(attribute: "male_count")
    femaleCount:                Int @rename(attribute: "female_count")
    permanentCount:             Int @rename(attribute: "permanent_count")
    temporaryCount:             Int @rename(attribute: "temporary_count")
    absentCount:                Int @rename(attribute: "absent_count")
    movedOutCount:              Int @rename(attribute: "moved_out_count")
    activeTemporaryResidences:  Int @rename(attribute: "active_temporary_residences")
    activeTemporaryAbsences:    Int @rename(attribute: "active_temporary_absences")
}

#import models/*.graphql
#import admin/*.graphql