##########################
########## QUERY
##########################
extend type Query @guard {
    "Danh sách đăng ký tạm trú"
    temporaryResidences(
        where: _ @whereConditions(columnsEnum: "TemporaryResidencesWhereColumn")
        orderBy: _ @orderBy(columnsEnum: "TemporaryResidencesOrderByColumn")
    ): [TemporaryResidence]
        @hasPermission(name: "view temporary residence")
        @paginate(defaultCount: 10)

    "Chi tiết một đăng ký tạm trú"
    temporaryResidence(id: ID! @eq): TemporaryResidence
        @hasPermission(name: "view temporary residence")
        @find
}
##########################
########## MUTATION
##########################
extend type Mutation @guard {
    "Đăng ký tạm trú"
    temporaryResidenceCreate(input: TemporaryResidenceCreateInput! @spread): TemporaryResidence
        @hasPermission(name: "create temporary residence")
        @field(resolver: "App\\GraphQL\\Mutations\\TemporaryResidence\\Create")
    "Cập nhật tạm trú"
    temporaryResidenceUpdate(input: TemporaryResidenceUpdateInput! @spread): TemporaryResidence
        @hasPermission(name: "update temporary residence")
        @field(resolver: "App\\GraphQL\\Mutations\\TemporaryResidence\\Update")
    "Xóa đăng ký tạm trú"
    temporaryResidenceDelete(id: ID! @whereKey): TemporaryResidence
        @hasPermission(name: "delete temporary residence")
        @delete
}
##########################
########## INPUT
##########################
input TemporaryResidenceCreateInput @validator(class: "TemporaryResidenceCreateInputValidator") {
    residentId: ID!     @rename(attribute: "resident_id")
    address: String!
    hostName: String    @rename(attribute: "host_name")
    fromDate: Date!     @rename(attribute: "from_date")
    toDate: Date        @rename(attribute: "to_date")
    reason: String
}

input TemporaryResidenceUpdateInput @validator(class: "TemporaryResidenceUpdateInputValidator") {
    id: ID!
    address: String
    hostName: String    @rename(attribute: "host_name")
    fromDate: Date      @rename(attribute: "from_date")
    toDate: Date        @rename(attribute: "to_date")
    reason: String
}
##########################
########## ENUM
##########################
enum TemporaryResidencesWhereColumn {
    RESIDENT_ID @enum(value: "resident_id")
    FROM_DATE   @enum(value: "from_date")
    TO_DATE     @enum(value: "to_date")
}

enum TemporaryResidencesOrderByColumn {
    FROM_DATE  @enum(value: "from_date")
    TO_DATE    @enum(value: "to_date")
    CREATED_AT @enum(value: "created_at")
}
##########################
########## TYPE
##########################
type TemporaryResidence {
    id: ID!
    resident: Resident! @belongsTo
    address: String!
    hostName: String    @rename(attribute: "host_name")
    fromDate: Date!     @rename(attribute: "from_date")
    toDate: Date        @rename(attribute: "to_date")
    reason: String
    createdAt: DateTime @rename(attribute: "created_at")
    updatedAt: DateTime @rename(attribute: "updated_at")
}
